### ISSUE TITLE
Compile failure on GlibC 2.26 because _NSIG is not defined

### ISSUE THREAD

**Issue by chrisr3** [01org/linux-sgx#160]
GlibC seems to have reorganised its header files between 2.25 and 2.26. Trying to compile against GlibC 2.26 results in this error:
```
setjmp/siglongjmp.c: In function ‘__nonworking_siglongjmp’:
setjmp/siglongjmp.c:96:31: error: ‘_NSIG’ undeclared (first use in this function)
    if (UNW_NUM_EH_REGS < 4 || _NSIG > 16 * sizeof (unw_word_t))
                               ^~~~~
setjmp/siglongjmp.c:96:31: note: each undeclared identifier is reported only once for each function it appears in
At top level:
setjmp/siglongjmp.c:51:20: warning: ‘__nonworking_siglongjmp’ defined but not used [-Wunused-function]
 #define siglongjmp __nonworking_siglongjmp
                    ^
setjmp/siglongjmp.c:57:1: note: in expansion of macro ‘siglongjmp’
 siglongjmp (sigjmp_buf env, int val)
 ^~~~~~~~~~
make[6]: *** [Makefile:2376: setjmp/siglongjmp.lo] Error 1
```
This seems to be because `/usr/include/sys/ucontext.h` no longers contains the line:
```C++
#include <signal.h>
```
where `ucontext.h` is included by `sdk/cpprt/linux/libunwind/include/libunwind-x86_64.h`

**Comment by llly** [comment]
Thanks. We'll update to improve compatibility.

**Comment by chrisr3** [comment]
OK, thanks. But I may have a deeper problem than a compilation failure here too. I've added
```C++
    #include <signal.h>
```
any now my binary compiles. But now it's failing to run on the SGX hardware:
```
[sig_handler sig_handler.cpp:94] signal handler is triggered
[sig_handler sig_handler.cpp:112] exception on ERESUME
[sig_handler sig_handler.cpp:150] NOT enclave signal
Illegal instruction (core dumped)
```
It looks like it's failing to read a stack guard, and then aborting:
```
#0  abort () at trts_pic.S:461
#1  0x00007fffe00169bd in __stack_chk_fail () at stack_chk.c:39
#2  0x00007fffe000f81c in init_stack_guard () at trts_nsp.cpp:65
#3  0x00007fffe000f9fd in do_init_thread (tcs=0x7fffebf9b000)
    at trts_nsp.cpp:94
#4  0x00007fffe000f720 in do_ecall (index=0, ms=0x7fffffffde10, 
    tcs=0x7fffebf9b000) at trts_ecall.cpp:147
#5  0x00007fffe000f3ff in enter_enclave (index=0, ms=0x7fffffffde10, 
    tcs=0x7fffebf9b000, cssa=0) at trts.cpp:303
#6  0x00007fffe0011103 in enclave_entry () at trts_pic.S:147
#7  0x00007ffff7ba752c in __morestack () at enter_enclave.S:53
#8  0x00007ffff7bb5cb8 in do_ecall (fn=0, 
    ocall_table=0x555555757d40 <ocall_table_java>, ms=0x7fffffffde10, 
    trust_thread=0x55555576eab0) at sig_handler.cpp:244
#9  0x00007ffff7bae492 in CEnclave::ecall (this=0x555555771b30, proc=0, 
    ocall_table=0x555555757d40 <ocall_table_java>, ms=0x7fffffffde10)
    at /home/chrisr3/workspace/corda-enterprise/sgx-jvm/linux-sgx/psw/urts/enclave.cpp:165
#10 0x00007ffff7bb1597 in sgx_ecall (enclave_id=2, proc=0, 
    ocall_table=0x555555757d40 <ocall_table_java>, ms=0x7fffffffde10)
    at /home/chrisr3/workspace/corda-enterprise/sgx-jvm/linux-sgx/psw/urts/routine.cpp:52
```

**Comment by lzha101** [comment]
Could you provide some info of your platform? What is your GCC version?

**Comment by chrisr3** [comment]
GCC version:
```bash
$ gcc --version
gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

GLibC version:
```bash
$ /lib64/libc.so.6 
GNU C Library (GNU libc) stable release version 2.25, by Roland McGrath et al.
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 7.1.1 20170630.
Available extensions:
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<https://bugs.archlinux.org/>.
```

**Comment by chrisr3** [comment]
Fixed.
